spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ansel
    username: ansel
    password: ansel
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties: {}
      #jakarta.persistence.schema-generation.scripts.action: create
      #jakarta.persistence.schema-generation.scripts.create-target: scripts/sql/000_gen.sql
      #jakarta.persistence.schema-generation.scripts.create-source: metadata

joinfaces:
  jsf:
    FACELETS_LIBRARIES: /WEB-INF/primefaces-diamond.taglib.xml;/WEB-INF/ansel.taglib.xml
  omnifaces:
    faces-views-scan-paths: /*.xhtml
  primefaces:
    theme: diamond-blue-light

server.error.path: /error